# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
#        image: nginx:latest
        build: ./docker/nginx/
        ports:
            - 8080:443
        volumes:
            - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
            - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
    git-server:
        build: ./docker/git/
        ports:
            - "2222:22"
        volumes:
            - ./git-server/keys:/git-server/keys
            - ./git-server/repos:/git-server/repos
