version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx:
        build: ./docker/nginx/
        ports:
            - 443:443
        volumes:
            - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
            - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
            - git-server:ro
       # environment:
        #    - COMPOSE_HTTP_TIMEOUT=120
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./web:/var/www/html
        #environment:
         #   - COMPOSE_HTTP_TIMEOUT=120
    git-server:
        build: ./docker/git/
        ports:
            - "22:22"
        volumes:
            - ./git-server/keys:/git-server/keys
            - ./git-server/repos:/git-server/repos
    copy:
        build: ./docker/copy/
        volumes_from:
            - php
            - git-server:ro
        tty: true
