version: "2"

services:
    nginx:
        build: ./docker/nginx/
        ports:
            - 443:443
        volumes:
            - ./ssl.conf/dhparam.pem:/etc/ssl/certs/dhparam.pem
            - ./ssl.conf/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./ssl.conf/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
            - git-server:ro
    php:
        image: php:7.0-fpm
        expose:
            - 9000
        volumes:
            - ./web:/var/www/html
    git-server:
        build: ./docker/git/
        ports:
            - "22:22"
        volumes:
            - ./git-server/keys:/git-server/keys
            - ./git-server/repos:/git-server/repos
    copy:
        build: ./docker/copy/
        volumes_from:
            - php
            - git-server:ro
        tty: true

